jwt:
  secret: ${JWT_SECRET:dGhpcy1pcy1hLXZlcnktbG9uZy1zZWNyZXQta2V5LWZvci1kZXZlbG9wbWVudC1vbmx5LTI1NmJpdA==}
  access-token-expiration: 900000
  refresh-token-expiration: 604800000

spring:
  application:
    name: assetmanagement

  data:
    redis:
      host: localhost
      port: 6379

  config:
    import: optional:vault://

  cloud:
    vault:
      host: localhost
      port: 8200
      scheme: http
      authentication: TOKEN
      token: myroot
      kv:
        enabled: true
        backend: secret
        default-context: assetmanagement

  datasource:
    url: jdbc:postgresql://localhost:5432/practice_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: true
      open-in-view: false
      properties:
        hibernate:
          format_sql: true
          default_batch_fetch_size: 20
    liquibase:
      change-log: classpath:db/changelog/db.changelog-master.yaml
      contexts: dev

  server:
    port: 8080

  logging:
    level:
      com.ibrahim.spring: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.orm.jdbc.bind: TRACE

